-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nmlt_open_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace NMLT.OpenKernel

/-- [nmlt_open_kernel::IndexTable]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 19:0-22:1
    Visibility: public -/
structure IndexTable where
  len : Std.Usize
  values : Array Std.Usize 4#usize

/-- [nmlt_open_kernel::StateMap]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 34:0-37:1
    Visibility: public -/
structure StateMap where
  len : Std.Usize
  values : Array Std.Usize 4#usize

/-- [nmlt_open_kernel::AtomTable]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 49:0-52:1
    Visibility: public -/
structure AtomTable where
  len : Std.Usize
  values : Array Std.U32 8#usize

/-- [nmlt_open_kernel::PredicateTable]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 64:0-67:1
    Visibility: public -/
structure PredicateTable where
  len : Std.Usize
  values : Array Bool 4#usize

/-- [nmlt_open_kernel::Grade]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 79:0-84:1
    Visibility: public -/
structure Grade where
  cost : Std.U64
  privacy : Std.U64
  energy : Std.U64
  uncertainty : Std.U32

/-- [nmlt_open_kernel::Resources]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 87:0-95:1
    Visibility: public -/
structure Resources where
  required : AtomTable
  consumed : AtomTable
  transferred : AtomTable
  received : AtomTable
  grade : Grade
  rely : AtomTable
  guarantees : AtomTable

/-- [nmlt_open_kernel::Action]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 117:0-124:1
    Visibility: public -/
structure Action where
  polarity : Std.U8
  channel : Std.U32
  assumption : PredicateTable
  guarantee : PredicateTable
  resources : Resources

/-- [nmlt_open_kernel::System]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 139:0-144:1
    Visibility: public -/
structure System where
  state_count : Std.Usize
  action_count : Std.Usize
  actions : Array Action 4#usize
  owned : AtomTable

/-- [nmlt_open_kernel::Refinement]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 158:0-161:1
    Visibility: public -/
structure Refinement where
  state_map : StateMap
  action_map : IndexTable

/-- [nmlt_open_kernel::ConnectionTable]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 164:0-168:1
    Visibility: public -/
structure ConnectionTable where
  len : Std.Usize
  left : Array Std.Usize 4#usize
  right : Array Std.Usize 4#usize

/-- [nmlt_open_kernel::Congruence]
    Source: 'crates/nmlt-open-kernel/src/lib.rs', lines 181:0-193:1
    Visibility: public -/
structure Congruence where
  payload_identity_present : Bool
  payload_variants_unique : Bool
  payload_cardinality : Std.Usize
  concrete_left : System
  abstract_left : System
  concrete_right : System
  abstract_right : System
  left_refinement : Refinement
  right_refinement : Refinement
  concrete_wiring : ConnectionTable
  abstract_wiring : ConnectionTable

end NMLT.OpenKernel
