import NMLT.Core.Transition
import NMLT.Core.TypedCore
import NMLT.Typing.Judgments
import NMLT.Metatheory.Soundness
import NMLT.Correspondence.M9Kernel
import NMLT.Behavior.ResourceBehavior
import NMLT.Behavior.ResourceWorld
import NMLT.Behavior.ResourceDynamics
import NMLT.Artifact.BehaviorCore
import NMLT.Artifact.SemanticClosure
import NMLT.Artifact.ExecutionWitness
import NMLT.Artifact.ExecutionLift
import NMLT.Examples.ResourceWorldTransfer
import NMLT.Examples.NestedResourceDynamics
import NMLT.Counterexamples.ResourceBehaviorControls
import NMLT.Counterexamples.ResourceWorldControls
